apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: web-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: python-web
  endpoints:
  - port: metrics
    interval: 15s
